---
title: "Data Cleaning and Benchmarking"
author: "Steven Kalt"
date: "Tuesday, June 23, 2015"
output: pdf_document
---

note: I will attempt to follow the google R styleguide, found here: http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#assignment 


The Fung institute has made accessible a list of cleantech patents from 1975-2012 at http://funglab.berkeley.edu/guanchengli/cleantech_patents.tsv, which I imported as 'cleantech.patents'

```{r imports, message = F}
# This chunk loads all required libraries for analysis.
require(lattice)
require(igraph)
```

```{r loadDataFrames}
# This chunk reads in data files and sets variable names

cleantech.patents <- read.delim(
  "~/PatentNetworks/Raw Data/cleantechPatents")
# cleantech.patents <- read.delim("//STORAGE/WagamanLab/SK Research Project/Data/cleantech_patents.tsv",

colnames(cleantech.patents) <- c("patent.number",
                                "assignee.name", 
                                "assignee.type",
                                "patent.title", 
                                "clean.type")
head(cleantech.patents)

assignees <- read.delim('~/PatentNetworks/Raw Data/assignee2.tsv', stringsAsFactors = F)[,-c(1,3,5:10)] 
assignees[,2] <- as.character(assignees[,2])
print(names(assignees ))

# These lines load the citation edgelist data.frames; since they're aroudn 2 Gb each, be prepared to wait up to 10 minutes.
citation00.10 <- read.csv("~/PatentNetworks/Raw Data/citation00_10.csv")
#citation00.10 <- read.csv("//STORAGE/WagamanLab/SK Research Project/Data/citation00_10.csv") # 8 minutes, latest timing
# citation75.99 <- read.csv("~/PatentNetworks/Raw Data/citation75_99.csv")
# citation75.99 <- read.csv("//STORAGE/WagamanLab/SK Research Project/Data/citation75_99.csv") 


# this variable is the original ordering of columns in the citation edgelist dataframes
citation.DF.Names <- c("patent.number.citing",
                     "citation.date",
                     "citation.name", 
                     "citation.kind",
                     "citation.country", 
                     "patent.number.cited",
                     "category",
                     "citation.seqence")
                             
colnames(citation00.10) <- citation.DF.Names
# colnames(citation75.99) <- citation.DF.Names
```


```{r delevel}
# both the 75.99 and 00.10 edgelists are factors; this code eliminates that and creates strings of the patent numbers in the place of the factors. Using as.numeric creates a significant number of NAs and should not be used since some patents are prefaced with a letter, such as "D0419273".  However, all the cleantech patents are pure 7-digit numeric patent numbers.

Delevel <- function(dfString){
  # changes the factors in the original citation data.frames into strings
  # 
  # Args:
  # dfString: the string of the name of the data frame (df) to be modified 
  df <- get(dfString)
  df$patent.number.citing <- levels(df$patent.number.citing)[df$patent.number.citing]
  df$patent.number.cited <- levels(df$patent.number.cited)[df$patent.number.cited]
  assign(dfString, df, envir = .GlobalEnv)
  }

Delevel("citation00.10")
# Delevel("citation75.99")
cleantech.patents$clean.type <- as.character(cleantech.patents$clean.type)
rm(Delevel)
```

```{r consolidateEdgelist}
# preparing to change the edgelist data.frames to igraph objects, their columns are reordered to make the variable order:
#                   (new order,              #former order)
citationDFNames <- c("patent.number.citing", #1
                     "patent.number.cited",  #6
                     "citation.date",        #2
                     "citationName",         #3
                     "citationKind",         #4
                     "citationCountry",      #5
                     "category",             #7
                     "citSeq")               #8

ConsolidateEdgelist <- function(dfString){
  # This function moves the citing and cited columns to be columns 1 and 2, respectively
  #
  # Args:
  # dfString: the string of the name of the data frame (df) to be modified 
  df <- get(dfString)
  df[,c(1:8)] <- df[,c(1,6,2:5,7,8)]
  names(df) <- citationDFNames
  assign(dfString, df, envir = .GlobalEnv)
  }

ConsolidateEdgelist("citation00.10")
# ConsolidateEdgelist("citation75.99")
rm(ConsolidateEdgelist)
```
```{r patent.numberStrings}
# Both the 75.99 and 00.10 dfs have their patent numbers in an 8-char format.  
patent.numbers <- unique(c(citation00.10[,1], citation00.10[,2]))
print(length(which(substring(patent.numbers,1,1) == '0'))/length(patent.numbers))
rm(patent.numbers)
# around half the patents in the 75.99 and 00.10 dataframes are prefaced with a zero.  All the cleantech patents, however, have 7-char patent numbers. Google also formats the addresses of patent grant webpages as google.com/patents/US1234567. Google's grant pages are the most readable format of a patent there is, so for convenience, I will format patent numbers as 7-character strings if they are prefaced with a zero.  If they are not, I will leave them as-is.   

Reformat.patent.numbers <- function(df.String){
  # This function removes the first leading zero from all 8-char patent 
  #
  # Args:
  # df.string: a string specifying the data.frame to be modified
  df <- get(df.String)
  a <- substring(df[,1],1,1) == '0'  # selects rows with leading zeroes
  b <- substring(df[,2],1,1) == '0'
  df[a, 1] <- substring(df[a,1],2)
  df[b, 2] <- substring(df[b,2],2)
  assign(df.String, df, envir = .GlobalEnv)
  }

Reformat.patent.numbers("citation00.10")
# Reformatpatent.numbers("citation75.99")
rm(Reformat.patent.numbers)
```


```{r makeGraph0010}
# First, make a graph from the 2000-2010 dataset's edgelist
g10 <- graph.data.frame(citation00.10[,c(1,2,3,7)]) 
# IGRAPH DN-- 7680630 37225313 -- 
# + attr: name (v/c), citation.date (e/c), category (e/c)
rm(citation00.10)
```

Since I'm only using the 00.10 graph in my analysis, I am leaving the code only for reading in the attributes of that graph alone. 
```{r readInAttrs}
# this chunk reads in patent attributes to the igraph object g10 : their disambiguated assignees and type of cleantech.  
verteces <- V(g10)$name # the patent numbers in the citation network
vids <- V(g10) # vertex ids
mat <- matrix(c(verteces,vids), ncol = 2)
colnames(mat) <- c("patent.number", "vid")
rm(verteces, vids)

cleantech.patents[,1] <- as.character(cleantech.patents[,1])
clean.attributes <- merge(mat, cleantech.patents[,c(1,4,5)], by = 1, all.x = T) # patent.number, patent.title, clean.type
clean.attributes$vid <- as.numeric(as.character(clean.attributes$vid))
rm(mat)
clean.attributes <- merge(clean.attributes, assignees, by = 1, all.x = T)
clean.attributes <- as.data.frame(clean.attributes)
brown.rows <- which(!(clean.attributes$clean.type %in% c("Wind",
                                                        "Solar",
                                                        "Hydro",
                                                        "Nuclear",
                                                        "Geothermal",
                                                        "Biofuel")
)
)
clean.attributes[brown.rows, 4] <- 'x'
V(g10)[clean.attributes$vid]$title <- clean.attributes$patent.title
V(g10)[clean.attributes$vid]$clean.type <- clean.attributes$clean.type
V(g10)[clean.attributes$vid]$assignee <- clean.attributes$Assignee
rm(clean.attributes, brown.rows)
```

```{r cleanNeighborhood}
# This chunk creates a subgraph, c10, from the neighborhood of the cleantech patents
green.vids <- which(V(g10)$clean.type != 'x')
green.neighborhood <- neighborhood(g10, 
                                   order = 1,
                                   nodes = green.vids,
                                   mode = "all")
green.neighborhood <- unique(unlist(green.neighborhood))
c10 <- induced.subgraph(g10, vids = green.neighborhood) # for cleantech graph 2000-2010
```
```{r memoChunk}
# this chunk saves the produced igraph objects for future use.  
#save(g10, file = "~/PatentNetworks/ProcessedData/g10.Rdata")
save(c10, file = "~/PatentNetworks/ProcessedData/c10.Rdata")
```

